name: Build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push
        uses: lsst-dm/build-and-push@main
        with:
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
          build-args: EUPS_TAG=test_2025_00
